#pragma once
#include "configure.h"
#ifdef HH103
#include "pins1xx.h"
#ifdef STM32F10X_MD
#define LED_HEARTBEAT       (PIN_PORT_C | PIN_NUM_13 | PIN_INIT_HIGH    | OUT_PP_02MHZ) // DEFAULT
#define LED_HEARTBEAT_ON		GPIOC->BSRR = PIN_MASK_13
#define LED_HEARTBEAT_OFF		GPIOC->BSRR = PIN_MASK_13 << PIN_MASK_SHIFT
#elif defined(STM32F10X_LD)
#define LED_HEARTBEAT       (PIN_PORT_A | PIN_NUM_15 | PIN_INIT_HIGH    | OUT_PP_02MHZ) // DEFAULT
#define LED_HEARTBEAT_ON		GPIOA->BSRR = PIN_MASK_15
#define LED_HEARTBEAT_OFF		GPIOA->BSRR = PIN_MASK_15 << PIN_MASK_SHIFT
#endif

#define LED_CAN_TX 			(PIN_PORT_B | PIN_NUM_03 | PIN_INIT_HIGH | OUT_PP_02MHZ)
#define LED_CAN_TX_ON		GPIOB->BSRR = PIN_MASK_03
#define LED_CAN_TX_OFF		GPIOB->BSRR = PIN_MASK_03 << PIN_MASK_SHIFT

#define LED_CAN_RX 			(PIN_PORT_B | PIN_NUM_04 | PIN_INIT_HIGH | OUT_PP_02MHZ)
#define LED_CAN_RX_ON		GPIOB->BSRR = PIN_MASK_04
#define LED_CAN_RX_OFF		GPIOB->BSRR = PIN_MASK_04 << PIN_MASK_SHIFT

#define LED_ERROR			(PIN_PORT_B | PIN_NUM_05 | PIN_INIT_HIGH | OUT_PP_02MHZ)
#define LED_ERROR_ON		GPIOB->BSRR = PIN_MASK_05
#define LED_ERROR_OFF		GPIOB->BSRR = PIN_MASK_05 << PIN_MASK_SHIFT

#ifdef USE_LCD
#define LCD_SPI_SCK				(PIN_PORT_B | PIN_NUM_13 | PIN_INIT_HIGH | AF_OPP_50MHZ)
#define LCD_SPI_MOSI			(PIN_PORT_B | PIN_NUM_15 | PIN_INIT_HIGH | AF_OPP_50MHZ)

#else
#define LED_HEATER_POWER		(PIN_PORT_B | PIN_NUM_15 | PIN_INIT_HIGH | OUT_PP_02MHZ)
#define LED_HEATER_POWER_ON		GPIOB->BSRR = PIN_MASK_15
#define LED_HEATER_POWER_OFF	GPIOB->BSRR = PIN_MASK_15 << PIN_MASK_SHIFT

#define LED_FANCOD_POWER		(PIN_PORT_B | PIN_NUM_14 | PIN_INIT_HIGH | OUT_PP_02MHZ)
#define LED_FANCOD_POWER_ON		GPIOB->BSRR = PIN_MASK_14
#define LED_FANCOD_POWER_OFF	GPIOB->BSRR = PIN_MASK_14 << PIN_MASK_SHIFT

#define LED_MOTOR_ENABLE		(PIN_PORT_B | PIN_NUM_13 | PIN_INIT_HIGH | OUT_PP_02MHZ)
#define LED_MOTOR_ENABLE_ON		GPI`OB->BSRR = PIN_MASK_13
#define LED_MOTOR_ENABLE_OFF	GPIOB->BSRR = PIN_MASK_13 << PIN_MASK_SHIFT

#define LED_MOTOR_POWER			(PIN_PORT_B | PIN_NUM_12 | PIN_INIT_HIGH | OUT_PP_02MHZ)
#define LED_MOTOR_POWER_ON		GPIOB->BSRR = PIN_MASK_12
#define LED_MOTOR_POWER_OFF		GPIOB->BSRR = PIN_MASK_12 << PIN_MASK_SHIFT
#endif

#define PIN_CAN_RX              (PIN_PORT_A | PIN_NUM_11 | PIN_INIT_PLUP    | IN_PULL_UP)
#define PIN_CAN_TX              (PIN_PORT_A | PIN_NUM_12 | PIN_INIT_HIGH    | AF_OPP_50MHZ)
#define PIN_ADC_CH0_A0        		(PIN_PORT_A | PIN_NUM_00  | PIN_INIT_HIZ     | ANALOG_IN )
#define PIN_ADC_CH1_A1        		(PIN_PORT_A | PIN_NUM_01  | PIN_INIT_HIZ     | ANALOG_IN )
////////////////////////////////////////////////////////////////////////////////
#endif
