/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"


#include "main.h"
static volatile uint32_t usTicks=0;
uint32_t 	i, result, temp, address, length;
uint32_t 	CanTrasmitMsgWaitCounter = 0;
uint32_t 	AdcReadWaitCounter = MAX_COUNTDOWN;
uint32_t	CanAddressAdcConvertCounter = MAX_COUNTDOWN;
uint8_t 	IsInitialized = 0;
uint8_t 	status = 0;
uint8_t 	CurrentHeadCanAddress = POSITION_UNPLUGGED; //current head position, which effects the working can bus address of packets sent and received
uint16_t	HeartbeatCounter = 0x1fff;

CanRxMsg 				CanRxMessage;
CanTxMsg 				CanTxMessage;
uint16_t				CanTxLedStatus = 0x0;
uint16_t				CanRxLedStatus = 0x0;
uint8_t					CanMessageReadyToRead = 0;
uint8_t					CanMessageReadyToSend = 0;
uint8_t 				CanTransmitMailbox;
uint8_t 				CanMessageBuffer[8] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07}; //this is a buffer for CAN message transmitting.
uint16_t 				CanRxTargetAddress; 	//Target Address of Received Can message
uint16_t 				CanRxSourceAddress; 	//Source Address of Received Can message
uint32_t				CanRxApplicationData;		//it would be filesize or offset for uploading/downloading firmware.
uint16_t 				CanRxFunctionId; 	//the Function identifier of Received Can message
uint8_t 				CanRxDataBuffer[8]; //the message data buffer of Received Can message

uint16_t                AddressAdcValue=0xFFFF;//invalid value until it starts updating
uint16_t				TempADCReading;

//the variables for Fireware Download/Upload
uint8_t 				IsDownloadApplication = 0;
uint32_t				DownloadApplicationWaitCounter = 0xffff;
uint32_t				DownloadApplicationAddress = 0;
uint8_t 				IsUploadApplication = 0;

FLASH_Status 			flashStatus = FLASH_COMPLETE;
__IO uint32_t 			flashTemp= 0;

// data from the Hot Head Resistor Value and 12-bit ADC Value spec
const HEADPOSITIONTABLE HeadPositionTable[HEAD_POSITION_ENTRIES] = {
	{  108, 91 }, // max adc value for hotbed1 position
	{  294, 26 }, // max adc value for yoke 2 aux2
	{  452, 16 }, // max adc value for yoke 1 aux2
	{  635, 21 }, // max adc value for yoke 2 hot head 1
	{  804, 11 }, // max adc value for yoke 1 hot head 1
	{  943, 22 }, // max adc value for yoke 2 hot head 2
	{ 1082, 12 }, // max adc value for yoke 1 hot head 2
	{ 1228, 23 }, // max adc value for yoke 2 hot head 3
	{ 1389, 13 }, // max adc value for yoke 1 hot head 3
	{ 1563, 24 }, // max adc value for yoke 2 hot head 4
	{ 1751, 14 }, // max adc value for yoke 1 hot head 4
	{ 1946, 25 }, // max adc value for yoke 2 aux1
	{ 2140, 15 }, // max adc value for yoke 1 aux1
	{ 2345, 92 }, // max adc value for hotbed2 position
	{ 2544, 46 }, // max adc value for yoke 4 aux2
	{ 2723, 36 }, // max adc value for yoke 3 aux2
	{ 2901, 41 }, // max adc value for yoke 4 hot head 1
	{ 3065, 31 }, // max adc value for yoke 3 hot head 1
	{ 3200, 42 }, // max adc value for yoke 4 hot head 2
	{ 3317, 32 }, // max adc value for yoke 3 hot head 2
	{ 3439, 43 }, // max adc value for yoke 4 hot head 3
	{ 3557, 33 }, // max adc value for yoke 3 hot head 3
	{ 3667, 44 }, // max adc value for yoke 4 hot head 4
	{ 3780, 34 }, // max adc value for yoke 3 hot head 4
	{ 3906, 45 }, // max adc value for yoke 4 aux1
	{ 4034, 35 }, // max adc value for yoke 3 aux1
	{ MAX_ADC, POSITION_UNPLUGGED } // max adc value an unplugged hothead
};

void InitRCC()
{
    // Update SystemCoreClock value
	//SystemCoreClockUpdate();
    // Configure the SysTick timer to overflow every 1 us
    SysTick_Config(SystemCoreClock / 1000000);
    //Enable GPIOA clock
	RCC->APB2ENR |= (RCC_APB2Periph_GPIOA);		//enable clock for peripheral
	RCC->APB2RSTR &= ~(RCC_APB2Periph_GPIOA);	//remove reset from peripheral
	//Enable GPIOB clock
	RCC->APB2ENR |= (RCC_APB2Periph_GPIOB);
	RCC->APB2RSTR &= ~(RCC_APB2Periph_GPIOB);

	//Enable AFIOEN clock
	RCC->APB2ENR |= (RCC_APB2ENR_AFIOEN);
	RCC->APB2RSTR &= ~(RCC_APB2ENR_AFIOEN);

	//Enable CAN1 clock

	RCC->APB1ENR |= (RCC_APB1Periph_CAN1);
	RCC->APB1RSTR &= ~(RCC_APB1Periph_CAN1);

}


// SysTick_Handler function will be called every 1 us
void SysTick_Handler(uint32_t us)
{
    if (usTicks != 0)
    {
        usTicks--;
    }
}

//////////////////////////GPIO FUNCTIONS////////////////////////////////////////////////

//Initialize the GPIO
void InitGPIO()
{
	AFIO->MAPR &= 0xf8ffffff;
	AFIO->MAPR |= 0x02000000; //FOR JTAG
#ifndef OPTIMIZE
	GPIO_InitTypeDef GPIO_InitStructure;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_2MHz;
	GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_Out_PP;

	//set pin  for Leds
	GPIO_InitStructure.GPIO_Pin   = LED_B_CANTX | LED_B_CANRX | LED_B_CANRXERROR|
									LED_HEADPOS_00 | LED_HEADPOS_01 | LED_HEADPOS_02| LED_HEADPOS_03;
	GPIO_Init(GPIOB, &GPIO_InitStructure);

	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_2MHz;
	GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_Out_PP;
	GPIO_InitStructure.GPIO_Pin   = LED_A_HEARTBEAT; //for heartbeat
	GPIO_Init(GPIOA, &GPIO_InitStructure);

	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_AF_PP;
	GPIO_InitStructure.GPIO_Pin   = CAN_A_TX;
	GPIO_Init(GPIOA, &GPIO_InitStructure);

	GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_IPU;
	GPIO_InitStructure.GPIO_Pin   = CAN_A_RX;
	GPIO_Init(GPIOA, &GPIO_InitStructure);

	GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_IPU;
	GPIO_InitStructure.GPIO_Pin   = SWITCH_B_LEFT | SWITCH_B_RIGHT;
	GPIO_Init(GPIOB, &GPIO_InitStructure);

#else
	GPIOA->CRH = PortAControlBits8_15;
	GPIOB->CRH = PortBControlBits8_15;
	GPIOB->CRL = PortBControlBits0_7;
#endif
	//Reset the Leds.
	GPIOA->BRR = LED_A_HEARTBEAT;
	GPIOB->BRR = LED_B_CANTX;
	GPIOB->BRR = LED_B_CANRX;
	GPIOB->BRR = LED_B_CANRXERROR;
}


//////////////////////////ADC FUNCTIONS/////////////////////////////////////////////////////////////////////


void InitADC()		// bootloader version
{
	RCC->CFGR &= CFGR_ADCPRE_Reset_Mask; 					//clock for ADC (max 14MHz --> 72/6=12MHz)
	RCC->CFGR |= RCC_PCLK2_Div6; // 0x0008000

	RCC->APB2ENR |= (RCC_APB2Periph_ADC1);
	RCC->APB2RSTR &= ~(RCC_APB2Periph_ADC1);

	//replace ADC_Init(ADC1, &ADC_InitStructure);   		//set config of ADC1
	ADC1->CR1 &= CR1_CLEAR_Mask;;
	ADC1->CR2 = (ADC1->CR2 & CR2_CLEAR_Mask) | ADC_ExternalTrigConv_None | 0x2;
	ADC1->SQR1 = ADC1->SQR1 & SQR1_CLEAR_Mask;

	//replace ADC_Cmd(ADC1,ENABLE);							//enable ADC1
	ADC1->CR2 |= CR2_ADON_Set;								//enable ADC1

	//  ADC calibration (optional, but recommended at power on)
	//replace ADC_ResetCalibration(ADC1);					// Reset previous calibration
	ADC1->CR2 |= CR2_RSTCAL_Set;
	//while(ADC_GetResetCalibrationStatus(ADC1));
	while(ADC1->CR2 & CR2_RSTCAL_Set);

	//replace ADC_StartCalibration(ADC1);					// Start new calibration (ADC must be off at that time)
	ADC1->CR2 |= CR2_CAL_Set;
	//ADC_GetCalibrationStatus(ADC1));
	while(ADC1->CR2 & CR2_CAL_Set) ; 			// Wait until calibration is complete

	// adcSetup
	//replaced:
	//ADC_RegularChannelConfig(ADC1, HH_ADC_CHANNEL_POS, 1, ADC_SampleTime_239Cycles5);
	ADC1->SMPR2 = 0x18000000;

	ADC1->SQR3 = 0x00000009;

	//replaced: ADC_Cmd(ADC1, ENABLE); //enable ADC1
	ADC1->CR2 |= CR2_ADON_Set;

	//replaced: ADC_SoftwareStartConvCmd(ADC1, ENABLE);		 // start conversion (will be endless as we are in continuous mode)
	ADC1->CR2 |= CR2_EXTTRIG_SWSTART_Set;
}

//Get the Can Head Address from ADC
void AdcConvertCanAddress()
{
	//TempADCReading= ADC1->DR;
	//StartNextConversion();//start it right away, so it has the most time to do the conversion
	if(AdcReadWaitCounter == MAX_COUNTDOWN) //When ADC value reading start.
	{
		ADC1->SQR3 |= (0<<0);
		ADC1->CR2 |= (1<<0);
	}
	AdcReadWaitCounter --;
	if(AdcReadWaitCounter == 0) //Time's up for reading ADC.
	{
		AdcReadWaitCounter = MAX_COUNTDOWN;
		return;
	}
	if(!(ADC1->SR & (1<<1)))return;//not a valid conversion, so leave without changing anything
	//AddressAdcValue += TempADCReading;//add the valid reading to the last value -------------------------|
	//AddressAdcValue /= 2;//now divide by 2, to perform an average, this will filter out noise -----------| I didn't understand.
	//AddressAdcValue = (ADC1->DR + AddressAdcValue) /2;
	if(AddressAdcValue < MAX_ADC) //it would be not be more than 2048(0x800)
		AddressAdcValue = (ADC1->DR + AddressAdcValue) /2; //now divide by 2, to perform an average, this will filter out noise
	else
		AddressAdcValue = ADC1->DR;
	AdcReadWaitCounter = MAX_COUNTDOWN;
}
//takes the current ADC converted value and adjust the calculates the head address based
// on the HEADPOSITIONTAABLE taable.
//this represents the value from a voltage drivider located on the head, and the yoke
//
void CalculateDevicePosition()
{
	if(AddressAdcValue>0x1000)return;//invalid data, try again later
	for (i = 0; i < HEAD_POSITION_ENTRIES; i++)
	{
		if (AddressAdcValue <= HeadPositionTable[i].adcRaw)
		{
			break;
		}
	}
	if (i == HEAD_POSITION_ENTRIES)
	{
		CurrentHeadCanAddress = POSITION_UNPLUGGED;
		return;
		//reportError1x32(ERROR_UNIT_ADC, ERROR_EXCEEDED_TABLE_LENGTH, (uint32_t)&_blDevicePositionTable[0]);
	}

	switch(HeadPositionTable[i].position)
	{
	case HEAD_01: SetPin(GPIOB, LED_HEADPOS_00); CurrentHeadCanAddress = HEAD_01; break;
	case HEAD_02: SetPin(GPIOB, LED_HEADPOS_01); CurrentHeadCanAddress = HEAD_02;break;
	case HEAD_03: SetPin(GPIOB, LED_HEADPOS_02); CurrentHeadCanAddress = HEAD_03;break;
	case HEAD_04: SetPin(GPIOB, LED_HEADPOS_03); CurrentHeadCanAddress = HEAD_04;break;
	}
}
/////////////////////////////////// CAN Functions //////////////////////////////////////////////////////////////////////

/**
  * @brief  Fills each CAN_InitStruct member with its default value.
  * @param  CAN_InitStruct: pointer to a CAN_InitTypeDef structure which
  *                         will be initialized.
  * @retval None.
  */
void CAN_StructInit(CAN_InitTypeDef* CAN_InitStruct)
{
  /* Reset CAN init structure parameters values */

  /* Initialize the time triggered communication mode */
  CAN_InitStruct->CAN_TTCM = DISABLE;

  /* Initialize the automatic bus-off management */
  CAN_InitStruct->CAN_ABOM = DISABLE;

  /* Initialize the automatic wake-up mode */
  CAN_InitStruct->CAN_AWUM = DISABLE;

  /* Initialize the no automatic retransmission */
  CAN_InitStruct->CAN_NART = DISABLE;

  /* Initialize the receive FIFO locked mode */
  CAN_InitStruct->CAN_RFLM = DISABLE;

  /* Initialize the transmit FIFO priority */
  CAN_InitStruct->CAN_TXFP = DISABLE;

  /* Initialize the CAN_Mode member */
  CAN_InitStruct->CAN_Mode = CAN_Mode_Normal;

  /* Initialize the CAN_SJW member */
  CAN_InitStruct->CAN_SJW = CAN_SJW_1tq;

  /* Initialize the CAN_BS1 member */
  CAN_InitStruct->CAN_BS1 = CAN_BS1_4tq;

  /* Initialize the CAN_BS2 member */
  CAN_InitStruct->CAN_BS2 = CAN_BS2_3tq;

  /* Initialize the CAN_Prescaler member */
  CAN_InitStruct->CAN_Prescaler = 1;
}

/**
  * @brief  Initializes the CAN peripheral according to the specified
  *         parameters in the CAN_InitStruct.
  * @param  CANx:           where x can be 1 or 2 to to select the CAN
  *                         peripheral.
  * @param  CAN_InitStruct: pointer to a CAN_InitTypeDef structure that
  *                         contains the configuration information for the
  *                         CAN peripheral.
  * @retval Constant indicates initialization succeed which will be
  *         CAN_InitStatus_Failed or CAN_InitStatus_Success.
  */
uint8_t CAN_Init(CAN_TypeDef* CANx, CAN_InitTypeDef* CAN_InitStruct)
{
  uint8_t InitStatus = CAN_InitStatus_Failed;
  uint32_t wait_ack = 0x00000000;

  /* Exit from sleep mode */
  CANx->MCR &= (~(uint32_t)CAN_MCR_SLEEP);

  /* Request initialisation */
  CANx->MCR |= CAN_MCR_INRQ ;

  /* Wait the acknowledge */
  while (((CANx->MSR & CAN_MSR_INAK) != CAN_MSR_INAK) && (wait_ack != INAK_TIMEOUT))
  {
    wait_ack++;
  }

  /* Check acknowledge */
  if ((CANx->MSR & CAN_MSR_INAK) != CAN_MSR_INAK)
  {
    InitStatus = CAN_InitStatus_Failed;
  }
  else
  {
    /* Set the time triggered communication mode */
    if (CAN_InitStruct->CAN_TTCM == ENABLE)
    {
      CANx->MCR |= CAN_MCR_TTCM;
    }
    else
    {
      CANx->MCR &= ~(uint32_t)CAN_MCR_TTCM;
    }

    /* Set the automatic bus-off management */
    if (CAN_InitStruct->CAN_ABOM == ENABLE)
    {
      CANx->MCR |= CAN_MCR_ABOM;
    }
    else
    {
      CANx->MCR &= ~(uint32_t)CAN_MCR_ABOM;
    }

    /* Set the automatic wake-up mode */
    if (CAN_InitStruct->CAN_AWUM == ENABLE)
    {
      CANx->MCR |= CAN_MCR_AWUM;
    }
    else
    {
      CANx->MCR &= ~(uint32_t)CAN_MCR_AWUM;
    }

    /* Set the no automatic retransmission */
    if (CAN_InitStruct->CAN_NART == ENABLE)
    {
      CANx->MCR |= CAN_MCR_NART;
    }
    else
    {
      CANx->MCR &= ~(uint32_t)CAN_MCR_NART;
    }

    /* Set the receive FIFO locked mode */
    if (CAN_InitStruct->CAN_RFLM == ENABLE)
    {
      CANx->MCR |= CAN_MCR_RFLM;
    }
    else
    {
      CANx->MCR &= ~(uint32_t)CAN_MCR_RFLM;
    }

    /* Set the transmit FIFO priority */
    if (CAN_InitStruct->CAN_TXFP == ENABLE)
    {
      CANx->MCR |= CAN_MCR_TXFP;
    }
    else
    {
      CANx->MCR &= ~(uint32_t)CAN_MCR_TXFP;
    }

    /* Set the bit timing register */
    CANx->BTR = (uint32_t)((uint32_t)CAN_InitStruct->CAN_Mode << 30) | \
                ((uint32_t)CAN_InitStruct->CAN_SJW << 24) | \
                ((uint32_t)CAN_InitStruct->CAN_BS1 << 16) | \
                ((uint32_t)CAN_InitStruct->CAN_BS2 << 20) | \
               ((uint32_t)CAN_InitStruct->CAN_Prescaler - 1);

    /* Request leave initialisation */
    CANx->MCR &= ~(uint32_t)CAN_MCR_INRQ;

   /* Wait the acknowledge */
   wait_ack = 0;

   while (((CANx->MSR & CAN_MSR_INAK) == CAN_MSR_INAK) && (wait_ack != INAK_TIMEOUT))
   {
     wait_ack++;
   }

    /* ...and check acknowledged */
    if ((CANx->MSR & CAN_MSR_INAK) == CAN_MSR_INAK)
    {
      InitStatus = CAN_InitStatus_Failed;
    }
    else
    {
      InitStatus = CAN_InitStatus_Success ;
    }
  }

  /* At this step, return the status of initialization */
  return InitStatus;
}

/**
  * @brief  Initializes the CAN peripheral according to the specified
  *         parameters in the CAN_FilterInitStruct.
  * @param  CAN_FilterInitStruct: pointer to a CAN_FilterInitTypeDef
  *                               structure that contains the configuration
  *                               information.
  * @retval None.
  */
void CAN_FilterInit(CAN_FilterInitTypeDef* CAN_FilterInitStruct)
{
  uint32_t filter_number_bit_pos = 0;

  filter_number_bit_pos = ((uint32_t)1) << CAN_FilterInitStruct->CAN_FilterNumber;

  /* Initialisation mode for the filter */
  CAN1->FMR |= FMR_FINIT;

  /* Filter Deactivation */
  CAN1->FA1R &= ~(uint32_t)filter_number_bit_pos;

  /* Filter Scale */
  if (CAN_FilterInitStruct->CAN_FilterScale == CAN_FilterScale_16bit)
  {
    /* 16-bit scale for the filter */
    CAN1->FS1R &= ~(uint32_t)filter_number_bit_pos;

    /* First 16-bit identifier and First 16-bit mask */
    /* Or First 16-bit identifier and Second 16-bit identifier */
    CAN1->sFilterRegister[CAN_FilterInitStruct->CAN_FilterNumber].FR1 =
    ((0x0000FFFF & (uint32_t)CAN_FilterInitStruct->CAN_FilterMaskIdLow) << 16) |
        (0x0000FFFF & (uint32_t)CAN_FilterInitStruct->CAN_FilterIdLow);

    /* Second 16-bit identifier and Second 16-bit mask */
    /* Or Third 16-bit identifier and Fourth 16-bit identifier */
    CAN1->sFilterRegister[CAN_FilterInitStruct->CAN_FilterNumber].FR2 =
    ((0x0000FFFF & (uint32_t)CAN_FilterInitStruct->CAN_FilterMaskIdHigh) << 16) |
        (0x0000FFFF & (uint32_t)CAN_FilterInitStruct->CAN_FilterIdHigh);
  }

  if (CAN_FilterInitStruct->CAN_FilterScale == CAN_FilterScale_32bit)
  {
    /* 32-bit scale for the filter */
    CAN1->FS1R |= filter_number_bit_pos;
    /* 32-bit identifier or First 32-bit identifier */
    CAN1->sFilterRegister[CAN_FilterInitStruct->CAN_FilterNumber].FR1 =
    ((0x0000FFFF & (uint32_t)CAN_FilterInitStruct->CAN_FilterIdHigh) << 16) |
        (0x0000FFFF & (uint32_t)CAN_FilterInitStruct->CAN_FilterIdLow);
    /* 32-bit mask or Second 32-bit identifier */
    CAN1->sFilterRegister[CAN_FilterInitStruct->CAN_FilterNumber].FR2 =
    ((0x0000FFFF & (uint32_t)CAN_FilterInitStruct->CAN_FilterMaskIdHigh) << 16) |
        (0x0000FFFF & (uint32_t)CAN_FilterInitStruct->CAN_FilterMaskIdLow);
  }

  /* Filter Mode */
  if (CAN_FilterInitStruct->CAN_FilterMode == CAN_FilterMode_IdMask)
  {
    /*Id/Mask mode for the filter*/
    CAN1->FM1R &= ~(uint32_t)filter_number_bit_pos;
  }
  else /* CAN_FilterInitStruct->CAN_FilterMode == CAN_FilterMode_IdList */
  {
    /*Identifier list mode for the filter*/
    CAN1->FM1R |= (uint32_t)filter_number_bit_pos;
  }

  /* Filter FIFO assignment */
  if (CAN_FilterInitStruct->CAN_FilterFIFOAssignment == CAN_Filter_FIFO0)
  {
    /* FIFO 0 assignation for the filter */
    CAN1->FFA1R &= ~(uint32_t)filter_number_bit_pos;
  }

  if (CAN_FilterInitStruct->CAN_FilterFIFOAssignment == CAN_Filter_FIFO1)
  {
    /* FIFO 1 assignation for the filter */
    CAN1->FFA1R |= (uint32_t)filter_number_bit_pos;
  }

  /* Filter activation */
  if (CAN_FilterInitStruct->CAN_FilterActivation == ENABLE)
  {
    CAN1->FA1R |= filter_number_bit_pos;
  }

  /* Leave the initialisation mode for the filter */
  CAN1->FMR &= ~FMR_FINIT;
}

void CAN_ITConfig(CAN_TypeDef* CANx, uint32_t CAN_IT, FunctionalState NewState)
{
    if (NewState != DISABLE)
  {
    /* Enable the selected CANx interrupt */
    CANx->IER |= CAN_IT;
  }
  else
  {
    /* Disable the selected CANx interrupt */
    CANx->IER &= ~CAN_IT;
  }
}

/**
  * @brief  Initializes the NVIC peripheral according to the specified
  *         parameters in the NVIC_InitStruct.
  * @param  NVIC_InitStruct: pointer to a NVIC_InitTypeDef structure that contains
  *         the configuration information for the specified NVIC peripheral.
  * @retval None
  */
void NVIC_Init(NVIC_InitTypeDef* NVIC_InitStruct)
{
  uint32_t tmppriority = 0x00, tmppre = 0x00, tmpsub = 0x0F;

   if (NVIC_InitStruct->NVIC_IRQChannelCmd != DISABLE)
  {
    /* Compute the Corresponding IRQ Priority --------------------------------*/
    tmppriority = (0x700 - ((SCB->AIRCR) & (uint32_t)0x700))>> 0x08;
    tmppre = (0x4 - tmppriority);
    tmpsub = tmpsub >> tmppriority;

    tmppriority = (uint32_t)NVIC_InitStruct->NVIC_IRQChannelPreemptionPriority << tmppre;
    tmppriority |=  NVIC_InitStruct->NVIC_IRQChannelSubPriority & tmpsub;
    tmppriority = tmppriority << 0x04;

    NVIC->IP[NVIC_InitStruct->NVIC_IRQChannel] = tmppriority;

    /* Enable the Selected IRQ Channels --------------------------------------*/
    NVIC->ISER[NVIC_InitStruct->NVIC_IRQChannel >> 0x05] =
      (uint32_t)0x01 << (NVIC_InitStruct->NVIC_IRQChannel & (uint8_t)0x1F);
  }
  else
  {
    /* Disable the Selected IRQ Channels -------------------------------------*/
    NVIC->ICER[NVIC_InitStruct->NVIC_IRQChannel >> 0x05] =
      (uint32_t)0x01 << (NVIC_InitStruct->NVIC_IRQChannel & (uint8_t)0x1F);
  }
}
void RCC_APB1PeriphResetCmd(uint32_t RCC_APB1Periph, FunctionalState NewState)
{
  /* Check the parameters */
  if (NewState != DISABLE)
  {
    RCC->APB1RSTR |= RCC_APB1Periph;
  }
  else
  {
    RCC->APB1RSTR &= ~RCC_APB1Periph;
  }
}
void CAN_DeInit(CAN_TypeDef* CANx)
{

  if (CANx == CAN1)
  {
    /* Enable CAN1 reset state */
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_CAN1, ENABLE);
    /* Release CAN1 from reset state */
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_CAN1, DISABLE);
  }

}
void InitCAN()
{
	/* CAN register init*/
		//First, Deinitializes the CAN peripheral registers to their default reset values.


#ifdef OPTIMIZE
	RCC->APB1RSTR |= RCC_APB1Periph_CAN1;  /* Enable CAN1 reset state */
	RCC->APB1RSTR &= ~RCC_APB1Periph_CAN1; /* Release CAN1 from reset state */

	temp = 0;
	//Initializes the CAN peripheral according to the specified         parameters in the CAN_InitStruct.(CAN_Init(CAN1, &CAN_InitStructure))
	/* Exit from sleep mode */
	CAN1->MCR &= (~(uint32_t)CAN_MCR_SLEEP);

	/* Request initialisation */
	CAN1->MCR |= CAN_MCR_INRQ ;

	/* Wait the acknowledge */
	while (((CAN1->MSR & CAN_MSR_INAK) != CAN_MSR_INAK) && (temp != INAK_TIMEOUT))
	{
		temp++;
	}
	/* Set the time triggered communication mode */
	CAN1->MCR &= ~(uint32_t)CAN_MCR_TTCM;  	//CAN_InitStructure.CAN_TTCM = DISABLE;
	/* Set the automatic bus-off management */
	CAN1->MCR &= ~(uint32_t)CAN_MCR_ABOM;	//CAN_InitStructure.CAN_ABOM = DISABLE;
	/* Set the automatic wake-up mode */
	CAN1->MCR &= ~(uint32_t)CAN_MCR_AWUM;
	/* Set the no automatic retransmission */
	CAN1->MCR &= ~(uint32_t)CAN_MCR_NART;	//CAN_InitStructure.CAN_NART = DISABLE;
	/* Set the receive FIFO locked mode */
	CAN1->MCR &= ~(uint32_t)CAN_MCR_RFLM;	//CAN_InitStructure.CAN_RFLM = DISABLE;
	/* Set the transmit FIFO priority */
	CAN1->MCR &= ~(uint32_t)CAN_MCR_TXFP;	//CAN_InitStructure.CAN_TXFP = DISABLE;

	/* Set the bit timing register */
	CAN1->BTR = (uint32_t)((uint32_t)CAN_Mode_Normal << 30) | \
				((uint32_t)CAN_SJW_1tq << 24) | \
				((uint32_t)CAN_BS1_3tq << 16) | \
				((uint32_t)CAN_BS2_5tq << 20) | \
			   ((uint32_t)8 - 1);
	/* Request leave initialisation */
	CAN1->MCR &= ~(uint32_t)CAN_MCR_INRQ;
	/* Wait the acknowledge */
	temp = 0;

	while (((CAN1->MSR & CAN_MSR_INAK) == CAN_MSR_INAK) && (temp != INAK_TIMEOUT))
	{
		temp++;
	}
	/*End of Initialized Can Init Structure.*/

	/*Initializes the CAN peripheral according to the specified parameters in the CAN_FilterInitStruct.*/
	CAN1->FMR |= FMR_FINIT;
	CAN1->FA1R &= ~(uint32_t)1;
	CAN1->FS1R |= 1;

	 /* 32-bit identifier or First 32-bit identifier */
	CAN1->sFilterRegister[0].FR1 = ((0x0000FFFF & (uint32_t)0) << 16) | (0x0000FFFF & (uint32_t)0);
	/* 32-bit mask or Second 32-bit identifier */
	CAN1->sFilterRegister[0].FR2 = ((0x0000FFFF & (uint32_t)0) << 16) | (0x0000FFFF & (uint32_t)0);

	CAN1->FM1R &= ~(uint32_t)1;
	CAN1->FFA1R |= (uint32_t)1;
	CAN1->FA1R |= 1;
	/* Leave the initialisation mode for the filter */
	CAN1->FMR &= ~FMR_FINIT;
	/*End of Initialized Can Filter Init Structure.*/

	/*Enables the specified CAN1 interrupts.*/
	CAN1->IER |= CAN_IT_FMP1;


	/*Initializes the NVIC peripheral according to the specified parameters in the NVIC_InitStruct.*/
	NVIC->IP[CAN1_RX1_IRQn] = 0;
	/* Enable the Selected IRQ Channels --------------------------------------*/
	NVIC->ISER[CAN1_RX1_IRQn >> 0x05] = (uint32_t)0x01 << (CAN1_RX1_IRQn & (uint8_t)0x1F);
#else
	CAN_InitTypeDef 		CAN_InitStructure;
	CAN_FilterInitTypeDef 	CAN_FilterInitStructure;
	NVIC_InitTypeDef 		NVIC_InitStructure;

	/* CAN register init*/
	CAN_DeInit(CAN1);
	CAN_StructInit(&CAN_InitStructure);

	/* CAN cell init*/
	CAN_InitStructure.CAN_TTCM = DISABLE;
	CAN_InitStructure.CAN_ABOM = DISABLE;
	CAN_InitStructure.CAN_AWUM = DISABLE;
	CAN_InitStructure.CAN_NART = DISABLE;
	CAN_InitStructure.CAN_RFLM = DISABLE;
	CAN_InitStructure.CAN_TXFP = DISABLE;
	CAN_InitStructure.CAN_Mode = CAN_Mode_Normal;// ;CAN_Mode_LoopBack is for debug.
	CAN_InitStructure.CAN_SJW = CAN_SJW_1tq;
	CAN_InitStructure.CAN_BS1 = CAN_BS1_3tq;
	CAN_InitStructure.CAN_BS2 = CAN_BS2_5tq;
	CAN_InitStructure.CAN_Prescaler = 8;
	CAN_Init(CAN1, &CAN_InitStructure);

	CAN_FilterInitStructure.CAN_FilterNumber = 0;
	CAN_FilterInitStructure.CAN_FilterMode = CAN_FilterMode_IdMask;
	CAN_FilterInitStructure.CAN_FilterScale = CAN_FilterScale_32bit;
	CAN_FilterInitStructure.CAN_FilterIdHigh = 0x0000;
	CAN_FilterInitStructure.CAN_FilterIdLow = 0x0000;
	CAN_FilterInitStructure.CAN_FilterMaskIdHigh = 0x0000;
	CAN_FilterInitStructure.CAN_FilterMaskIdLow = 0x0000;
	CAN_FilterInitStructure.CAN_FilterFIFOAssignment = 1;
	CAN_FilterInitStructure.CAN_FilterActivation = ENABLE;
	CAN_FilterInit(&CAN_FilterInitStructure);

	/* IT Configuration for CAN1 */
	CAN_ITConfig(CAN1, CAN_IT_FMP0,ENABLE);

	NVIC_InitStructure.NVIC_IRQChannel =  CAN1_RX1_IRQn;
	NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0x0;
	NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0x0;
	NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&NVIC_InitStructure);
#endif
}
/**
  * @brief  Receives a message.
  * @param  CANx:       where x can be 1 or 2 to to select the CAN peripheral.
  * @param  FIFONumber: Receive FIFO number, CAN_FIFO0 or CAN_FIFO1.
  * @param  RxMessage:  pointer to a structure receive message which contains
  *                     CAN Id, CAN DLC, CAN datas and FMI number.
  * @retval None.
  */
void CAN_Receive(CAN_TypeDef* CANx, uint8_t FIFONumber, CanRxMsg* RxMessage)
{
  /* Check the parameters */
  /* Get the Id */
  RxMessage->IDE = (uint8_t)0x04 & CANx->sFIFOMailBox[FIFONumber].RIR;
  if (RxMessage->IDE == CAN_Id_Standard)
  {
    RxMessage->StdId = (uint32_t)0x000007FF & (CANx->sFIFOMailBox[FIFONumber].RIR >> 21);
  }
  else
  {
    RxMessage->ExtId = (uint32_t)0x1FFFFFFF & (CANx->sFIFOMailBox[FIFONumber].RIR >> 3);
  }

  RxMessage->RTR = (uint8_t)0x02 & CANx->sFIFOMailBox[FIFONumber].RIR;
  /* Get the DLC */
  RxMessage->DLC = (uint8_t)0x0F & CANx->sFIFOMailBox[FIFONumber].RDTR;
  /* Get the FMI */
  RxMessage->FMI = (uint8_t)0xFF & (CANx->sFIFOMailBox[FIFONumber].RDTR >> 8);
  /* Get the data field */
  RxMessage->Data[0] = (uint8_t)0xFF & CANx->sFIFOMailBox[FIFONumber].RDLR;
  RxMessage->Data[1] = (uint8_t)0xFF & (CANx->sFIFOMailBox[FIFONumber].RDLR >> 8);
  RxMessage->Data[2] = (uint8_t)0xFF & (CANx->sFIFOMailBox[FIFONumber].RDLR >> 16);
  RxMessage->Data[3] = (uint8_t)0xFF & (CANx->sFIFOMailBox[FIFONumber].RDLR >> 24);
  RxMessage->Data[4] = (uint8_t)0xFF & CANx->sFIFOMailBox[FIFONumber].RDHR;
  RxMessage->Data[5] = (uint8_t)0xFF & (CANx->sFIFOMailBox[FIFONumber].RDHR >> 8);
  RxMessage->Data[6] = (uint8_t)0xFF & (CANx->sFIFOMailBox[FIFONumber].RDHR >> 16);
  RxMessage->Data[7] = (uint8_t)0xFF & (CANx->sFIFOMailBox[FIFONumber].RDHR >> 24);
  /* Release the FIFO */
  /* Release FIFO0 */
  if (FIFONumber == CAN_FIFO0)
  {
    CANx->RF0R |= CAN_RF0R_RFOM0;
  }
  /* Release FIFO1 */
  else /* FIFONumber == CAN_FIFO1 */
  {
    CANx->RF1R |= CAN_RF1R_RFOM1;
  }
}

//THis function is a callback for Receiving CAN Message.
void CAN1_RX1_IRQHandler()
{
	CAN_Receive(CAN1, CAN_FIFO1, &CanRxMessage);
	CanRxTargetAddress = (CanRxMessage.ExtId >> 16) & 0xFF;
	if(CanRxTargetAddress == CurrentHeadCanAddress) //if Head Address is same as Can message Head identifier.
	{
		switch((CanRxMessage.ExtId >> 24) & 0xFF)
		{
		case CAN_NORMAL_MESSAGE: // Normal function message;
			//if(IsDownloadFirware || IsUploadFirware) return; //because it is very busy, it will not be response to anyone

			CanRxFunctionId = CanRxMessage.ExtId  & 0xff;
			CanRxSourceAddress = (CanRxMessage.ExtId >> 8 )& 0xFF;
			break;
		case CAN_UPLOAD_START_APPLICATION:
		case CAN_UPLOADING_APPLICATION:
		case CAN_UPLOAD_END_APPLICATION:
		case CAN_DOWNLOAD_START_APPLICATION:
		case CAN_DOWNLOADING_APPLICATION:
		case CAN_DOWNLOAD_END_APPLICATION:
			CanRxFunctionId = (CanRxMessage.ExtId >> 24) & 0xff;
			CanRxSourceAddress = CAN_DEV_ANALYST;
			CanRxApplicationData = CanRxMessage.ExtId & 0xffff;
			break;
		}

		memcpy(CanRxDataBuffer, CanRxMessage.Data, CanRxMessage.DLC);
		CanMessageReadyToRead = 1;
	}
}

//////////////////////////////////////////////////
//this function is for sending message thru CAN.
//
// param:
//		target is a head number to send message.
//		funcId means the function identifier of message.
//		data is buffer to send. it must be less than 8bytes.
//		size is the length of buffer.

void SendCanMessage(uint16_t target, uint8_t funcId, uint8_t* data, uint8_t size)
{
	temp = (target << 16) + (CurrentHeadCanAddress << 8) + funcId; //this is Ext ID
	//CanTxMessage.RTR= CAN_RTR_DATA;
	//CanTxMessage.IDE= CAN_ID_EXT;
	//CanTxMessage.DLC= size;  //the data size to send, which would be smaller than 8bytes.
	if(size > 0) memcpy(CanTxMessage.Data, data, size); // copy the data to TxMessage's buffer

	/* Select one empty transmit mailbox */
	if ((CAN1->TSR&CAN_TSR_TME0) == CAN_TSR_TME0)
	{
		CanTransmitMailbox = 0;
	}
	else if ((CAN1->TSR&CAN_TSR_TME1) == CAN_TSR_TME1)
	{
		CanTransmitMailbox = 1;
	}
	else if ((CAN1->TSR&CAN_TSR_TME2) == CAN_TSR_TME2)
	{
		CanTransmitMailbox = 2;
	}
	else
	{
		CanTransmitMailbox = CAN_TxStatus_NoMailBox;
	}

	if (CanTransmitMailbox != CAN_TxStatus_NoMailBox) {
		CAN1->sTxMailBox[CanTransmitMailbox].TIR &= TMIDxR_TXRQ;

		CAN1->sTxMailBox[CanTransmitMailbox].TIR |= ((temp << 3) | \
													CAN_Id_Extended | \
														CAN_RTR_Data);

		/* Set up the DLC */

		CAN1->sTxMailBox[CanTransmitMailbox].TDTR &= (uint32_t)0xFFFFFFF0;
		CAN1->sTxMailBox[CanTransmitMailbox].TDTR |= size; //Data Size

		/* Set up the data field */
		CAN1->sTxMailBox[CanTransmitMailbox].TDLR = (((uint32_t)data[3] << 24) |
												 ((uint32_t)data[2] << 16) |
												 ((uint32_t)data[1] << 8) |
												 ((uint32_t)data[0]));
		CAN1->sTxMailBox[CanTransmitMailbox].TDHR = (((uint32_t)data[7] << 24) |
												 ((uint32_t)data[6] << 16) |
												 ((uint32_t)data[5] << 8) |
												 ((uint32_t)data[4]));
		/* Request transmission */
		CAN1->sTxMailBox[CanTransmitMailbox].TIR |= TMIDxR_TXRQ;
	}
	//CanTransmitMailbox = CAN_Transmit(CAN1, &CanTxMessage);
	CanTrasmitMsgWaitCounter = 0xFFFF; //it would be count down until Can trasmit is ok..
}

/**
  * @brief  Checks the transmission of a message.
  * @param  CANx:            where x can be 1 or 2 to to select the
  *                          CAN peripheral.
  * @param  TransmitMailbox: the number of the mailbox that is used for
  *                          transmission.
  * @retval CAN_TxStatus_Ok if the CAN driver transmits the message, CAN_TxStatus_Failed
  *         in an other case.
  */
uint8_t CAN_TransmitStatus(CAN_TypeDef* CANx, uint8_t TransmitMailbox)
{
  uint32_t state = 0;


  switch (TransmitMailbox)
  {
    case (CAN_TXMAILBOX_0):
      state =   CANx->TSR &  (CAN_TSR_RQCP0 | CAN_TSR_TXOK0 | CAN_TSR_TME0);
      break;
    case (CAN_TXMAILBOX_1):
      state =   CANx->TSR &  (CAN_TSR_RQCP1 | CAN_TSR_TXOK1 | CAN_TSR_TME1);
      break;
    case (CAN_TXMAILBOX_2):
      state =   CANx->TSR &  (CAN_TSR_RQCP2 | CAN_TSR_TXOK2 | CAN_TSR_TME2);
      break;
    default:
      state = CAN_TxStatus_Failed;
      break;
  }
  switch (state)
  {
      /* transmit pending  */
    case (0x0): state = CAN_TxStatus_Pending;
      break;
      /* transmit failed  */
     case (CAN_TSR_RQCP0 | CAN_TSR_TME0): state = CAN_TxStatus_Failed;
      break;
     case (CAN_TSR_RQCP1 | CAN_TSR_TME1): state = CAN_TxStatus_Failed;
      break;
     case (CAN_TSR_RQCP2 | CAN_TSR_TME2): state = CAN_TxStatus_Failed;
      break;
      /* transmit succeeded  */
    case (CAN_TSR_RQCP0 | CAN_TSR_TXOK0 | CAN_TSR_TME0):state = CAN_TxStatus_Ok;
      break;
    case (CAN_TSR_RQCP1 | CAN_TSR_TXOK1 | CAN_TSR_TME1):state = CAN_TxStatus_Ok;
      break;
    case (CAN_TSR_RQCP2 | CAN_TSR_TXOK2 | CAN_TSR_TME2):state = CAN_TxStatus_Ok;
      break;
    default: state = CAN_TxStatus_Failed;
      break;
  }
  return (uint8_t) state;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/**
  * @brief  Resets the RCC clock configuration to the default reset state.
  * @param  None
  * @retval None
  */
void RCC_DeInit(void)
{
  /* Set HSION bit */
  RCC->CR |= (uint32_t)0x00000001;

  /* Reset SW, HPRE, PPRE1, PPRE2, ADCPRE and MCO bits */
  RCC->CFGR &= (uint32_t)0xF8FF0000;

  /* Reset HSEON, CSSON and PLLON bits */
  RCC->CR &= (uint32_t)0xFEF6FFFF;

  /* Reset HSEBYP bit */
  RCC->CR &= (uint32_t)0xFFFBFFFF;

  /* Reset PLLSRC, PLLXTPRE, PLLMUL and USBPRE/OTGFSPRE bits */
  RCC->CFGR &= (uint32_t)0xFF80FFFF;

  /* Disable all interrupts and clear pending bits  */
  RCC->CIR = 0x009F0000;

}

void DeinitEverything()
{
	__HAL_RCC_GPIOC_CLK_DISABLE();
	__HAL_RCC_GPIOD_CLK_DISABLE();
	__HAL_RCC_GPIOB_CLK_DISABLE();
	__HAL_RCC_GPIOA_CLK_DISABLE();
	__HAL_RCC_TIM1_CLK_DISABLE();
	__HAL_RCC_SPI1_CLK_DISABLE();
	__HAL_RCC_USART1_CLK_DISABLE();

	RCC_DeInit();

	__HAL_RCC_APB1_FORCE_RESET();
	__HAL_RCC_APB1_RELEASE_RESET();
	__HAL_RCC_APB2_FORCE_RESET();
	__HAL_RCC_APB2_RELEASE_RESET();

	SysTick->CTRL = 0;
	SysTick->LOAD = 0;
	SysTick->VAL = 0;
}

void jumpToApp(const uint32_t address)
{
	const JumpStruct* vector_p = (JumpStruct*)address;
	DeinitEverything();
	SCB->VTOR = FLASH_APPLICATION_OFFSET_ADDRESS;

	/* let's do The Jump! */
    /* Jump, used asm to avoid stack optimization */
    asm("msr msp, %0; bx %1;" : : "r"(vector_p->stack_addr), "r"(vector_p->func_p));
}

//////////////////////////////////////// Flash functions ///////////////////////////////////////////

/**
  * @brief  Unlocks the FLASH Program Erase Controller.
  * @note   This function can be used for all STM32F10x devices.
  *         - For STM32F10X_XL devices this function unlocks Bank1 and Bank2.
  *         - For all other devices it unlocks Bank1 and it is equivalent
  *           to FLASH_UnlockBank1 function..
  * @param  None
  * @retval None
  */
void FLASH_Unlock(void)
{
  /* Authorize the FPEC of Bank1 Access */
  FLASH->KEYR = FLASH_KEY1;
  FLASH->KEYR = FLASH_KEY2;
}

/**
  * @brief  Locks the FLASH Program Erase Controller.
  * @note   This function can be used for all STM32F10x devices.
  *         - For STM32F10X_XL devices this function Locks Bank1 and Bank2.
  *         - For all other devices it Locks Bank1 and it is equivalent
  *           to FLASH_LockBank1 function.
  * @param  None
  * @retval None
  */
void FLASH_Lock(void)
{
  /* Set the Lock Bit to lock the FPEC and the CR of  Bank1 */
  FLASH->CR |= CR_LOCK_Set;
}


/**
  * @brief  Clears the FLASH's pending flags.
  * @note   This function can be used for all STM32F10x devices.
  *         - For STM32F10X_XL devices, this function clears Bank1 or Bank2’s pending flags
  *         - For other devices, it clears Bank1’s pending flags.
  * @param  FLASH_FLAG: specifies the FLASH flags to clear.
  *   This parameter can be any combination of the following values:
  *     @arg FLASH_FLAG_PGERR: FLASH Program error flag
  *     @arg FLASH_FLAG_WRPRTERR: FLASH Write protected error flag
  *     @arg FLASH_FLAG_EOP: FLASH End of Operation flag
  * @retval None
  */
void FLASH_ClearFlag(uint32_t FLASH_FLAG)
{
  /* Clear the flags */
  FLASH->SR = FLASH_FLAG;
}

/**
  * @brief  Returns the FLASH Bank1 Status.
  * @note   This function can be used for all STM32F10x devices, it is equivalent
  *         to FLASH_GetStatus function.
  * @param  None
  * @retval FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PG,
  *         FLASH_ERROR_WRP or FLASH_COMPLETE
  */
FLASH_Status FLASH_GetBank1Status(void)
{

  if((FLASH->SR & FLASH_FLAG_BANK1_BSY) == FLASH_FLAG_BSY)
  {
    flashStatus = FLASH_BUSY;
  }
  else
  {
    if((FLASH->SR & FLASH_FLAG_BANK1_PGERR) != 0)
    {
      flashStatus = FLASH_ERROR_PG;
    }
    else
    {
      if((FLASH->SR & FLASH_FLAG_BANK1_WRPRTERR) != 0 )
      {
        flashStatus = FLASH_ERROR_WRP;
      }
      else
      {
        flashStatus = FLASH_COMPLETE;
      }
    }
  }
  /* Return the Flash Status */
  return flashStatus;
}
/**
  * @brief  Waits for a Flash operation to complete or a TIMEOUT to occur.
  * @note   This function can be used for all STM32F10x devices,
  *         it is equivalent to FLASH_WaitForLastBank1Operation.
  *         - For STM32F10X_XL devices this function waits for a Bank1 Flash operation
  *           to complete or a TIMEOUT to occur.
  *         - For all other devices it waits for a Flash operation to complete
  *           or a TIMEOUT to occur.
  * @param  Timeout: FLASH programming Timeout
  * @retval FLASH Status: The returned value can be: FLASH_ERROR_PG,
  *         FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
  */
FLASH_Status FLASH_WaitForLastOperation(uint32_t Timeout)
{
	flashStatus = FLASH_COMPLETE;

  /* Check for the Flash Status */
	flashStatus = FLASH_GetBank1Status();
  /* Wait for a Flash operation to complete or a TIMEOUT to occur */
	while((flashStatus == FLASH_BUSY) && (Timeout != 0x00))
	{
		flashStatus = FLASH_GetBank1Status();
		Timeout--;
  	}
	if(Timeout == 0x00 )
  	{
  		flashStatus = FLASH_TIMEOUT;
  	}
  /* Return the operation status */
	return flashStatus;
}


/**
  * @brief  Erases a specified FLASH page.
  * @note   This function can be used for all STM32F10x devices.
  * @param  Page_Address: The page address to be erased.
  * @retval FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PG,
  *         FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
  */
FLASH_Status FLASH_ErasePage(uint32_t Page_Address)
{
  /* Wait for last operation to be completed */
  if(FLASH_WaitForLastOperation(EraseTimeout) != FLASH_COMPLETE) return FLASH_ERROR_PG;
  /* if the previous operation is completed, proceed to erase the page */
	FLASH->CR|= CR_PER_Set;
	FLASH->AR = Page_Address;
	FLASH->CR|= CR_STRT_Set;

	/* Wait for last operation to be completed */
	FLASH_WaitForLastOperation(EraseTimeout);
	/* Disable the PER Bit */
	FLASH->CR &= CR_PER_Reset;

  /* Return the Erase Status */
	return FLASH_COMPLETE;
}

/**
  * @brief  Programs a word at a specified address.
  * @note   This function can be used for all STM32F10x devices.
  * @param  Address: specifies the address to be programmed.
  * @param  Data: specifies the data to be programmed.
  * @retval FLASH Status: The returned value can be: FLASH_ERROR_PG,
  *         FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
  */
FLASH_Status FLASH_ProgramWord(uint32_t Address, uint32_t Data)
{
  /* Wait for last operation to be completed */
  flashStatus = FLASH_WaitForLastOperation(ProgramTimeout);

  if(flashStatus == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to program the new first
    half word */
    FLASH->CR |= CR_PG_Set;

    *(__IO uint16_t*)Address = (uint16_t)Data;
    /* Wait for last operation to be completed */
    flashStatus = FLASH_WaitForLastOperation(ProgramTimeout);

    if(flashStatus == FLASH_COMPLETE)
    {
      /* if the previous operation is completed, proceed to program the new second
      half word */
      flashTemp = Address + 2;

      *(__IO uint16_t*) flashTemp = Data >> 16;

      /* Wait for last operation to be completed */
      flashStatus = FLASH_WaitForLastOperation(ProgramTimeout);

      /* Disable the PG Bit */
      FLASH->CR &= CR_PG_Reset;
    }
    else
    {
      /* Disable the PG Bit */
      FLASH->CR &= CR_PG_Reset;
    }
  }

  /* Return the Program Status */
  return flashStatus;
}



// Erase the flash memory with StartAddress and length.
// 		StartAddress : the start Address of flash to erase
//		length : the length of range
//

uint8_t EraseFlash(uint32_t StartAddress, uint32_t size)
{
	result = SUCCESS;
	FLASH_Unlock();
	temp = (size / FLASH_PAGE_SIZE) + 2; // calculate the page size of erase range.
	FLASH_ClearFlag(FLASH_FLAG_BSY | FLASH_FLAG_EOP | FLASH_FLAG_PGERR | FLASH_FLAG_WRPRTERR);
	//FLASH_ClearFlag(FLASH_FLAG_EOP | FLASH_FLAG_OPTERR | FLASH_FLAG_WRPRTERR);
	for(i = 0; i < temp; i ++)
	{
		if(FLASH_ErasePage(StartAddress +  i * FLASH_PAGE_SIZE) != FLASH_COMPLETE)
		{
			result = ERROR;
			break;
		}
	}
	FLASH_Lock();
	return result;
}
//Write the 32bit data at the address in Flash.
uint8_t WriteFlash(uint32_t address, uint32_t data)
{
	result = SUCCESS;
	FLASH_Unlock();

	if(FLASH_ProgramWord(address, data) != FLASH_COMPLETE)
	{
		result = SUCCESS;
	}

	FLASH_Lock();
	return result;
}

//Write the 8bytes data at the address in Flash.
uint8_t WriteFlash8Bytes(uint32_t addr, uint8_t* data)
{
	result = SUCCESS;
	temp = BYTE2UINT32(data[3], data[2], data[1], data[0]);

	FLASH_Unlock();

	if(FLASH_ProgramWord(addr, temp) != FLASH_COMPLETE)
	{
		result = ERROR;
	}else {
		temp = BYTE2UINT32(data[7], data[6], data[5], data[4]);
		if(FLASH_ProgramWord(addr+ 4, temp) != FLASH_COMPLETE)
		{
			result = ERROR;
		}
	}

	FLASH_Lock();
	return result;
}

//Read the 8bytes data at the address in Flash.
void ReadFlash8Bytes(uint32_t addr, uint8_t* data) //data is 8bytes.
{
	for(i = 0; i < 8; i ++)
		data[i] = *(__IO uint8_t*)(addr+i);
}
uint32_t ReadFlash(uint32_t addr)
{
	temp= *(__IO uint32_t*)(addr);
	return temp;

}


////////////////////////////////////////////////////////////////////////////////////////////

void processCanMsgFunction()
{
	address = BYTE2UINT32(CanRxDataBuffer[3], CanRxDataBuffer[2], CanRxDataBuffer[1],CanRxDataBuffer[0]);
	temp = BYTE2UINT32(CanRxDataBuffer[7], CanRxDataBuffer[6], CanRxDataBuffer[5],CanRxDataBuffer[4]);

	switch(CanRxFunctionId)
	{
	case CAN_FUNCTION_PING: // Response for request ping
		//PingCanMessage(CanRxSourceAddress, 0);
		SendCanMessage(CAN_DEV_ANALYST, CAN_FUNCTION_PING, CanMessageBuffer, 0);
		break;
	case CAN_FUNCTION_BLINK_HEARTBEAT:
		break;
	case CAN_FUNCTION_JUMP_TO_APPLICATION:
		//applicationMain();
		jumpToApp(FLASH_APPLICATION_START_ADDRESS);
		break;
	case CAN_FUNCTION_ERASE_FLASH:
		//Data Format: [0-3]: Start Address, [4-7]: Length
		length = BYTE2UINT32(CanRxDataBuffer[7], CanRxDataBuffer[6],CanRxDataBuffer[5],CanRxDataBuffer[4]);
		result = EraseFlash(address, length);
		CanMessageBuffer[0] = result;
		SendCanMessage(CanRxSourceAddress, CAN_FUNCTION_ERASE_FLASH, CanMessageBuffer, 8);
		break;

	case CAN_FUNCTION_WRITE_FLASH:
		//Data Format: [0-3]: Start Address, [4-7]: Data 4bytes
		temp = WriteFlash(address, temp);
		CanMessageBuffer[0] = result;
		SendCanMessage(CanRxSourceAddress, CAN_FUNCTION_WRITE_FLASH, CanMessageBuffer, 8);
		break;

	case CAN_FUNCTION_READ_FLASH:
		//Data Format: [0-3]: Start Address,
		ReadFlash8Bytes(address, CanMessageBuffer); //Read the 8Byte data at the address.
		SendCanMessage(CanRxSourceAddress, CAN_FUNCTION_READ_FLASH, CanMessageBuffer, 8);
		break;

	case CAN_UPLOAD_START_APPLICATION:
		//CanRxApplicationData is file size of firmware to upload.
		//it needs to erase the flash memory range to upload.
		length = CanRxApplicationData;
		result = EraseFlash(FLASH_APPLICATION_SIZE_ADDRESS, CanRxApplicationData); //Add the one page size to register the file size.
		if(result == ERROR)
		{
			//send the error message to Can Analyst-2
			SendCanMessage(CAN_DEV_ANALYST, CAN_APPLICATION_UPLOADDOWNLOAD_ERROR, CanMessageBuffer, 0);
			IsUploadApplication = 0;
		}
		else
		{
			//at the 0x08004000 address, it write the application file size.
			result = WriteFlash(FLASH_APPLICATION_SIZE_ADDRESS, length);
			if(result == ERROR)
			{
				SendCanMessage(CAN_DEV_ANALYST, CAN_APPLICATION_UPLOADDOWNLOAD_ERROR, CanMessageBuffer, 0);
				IsUploadApplication = 0;
			}else
			{
				IsUploadApplication = 1;
			}
		}
		break;
	case CAN_UPLOADING_APPLICATION:
		result = WriteFlash8Bytes(FLASH_APPLICATION_START_ADDRESS + CanRxApplicationData, CanRxDataBuffer);
		if(result == ERROR)
		{
			SendCanMessage(CAN_DEV_ANALYST, CAN_APPLICATION_UPLOADDOWNLOAD_ERROR, CanMessageBuffer, 0);
			IsUploadApplication = 0;
		}
		break;
	case CAN_UPLOAD_END_APPLICATION:
		//Notify the upload end.
		SendCanMessage(CAN_DEV_ANALYST, CAN_APPLICATION_UPLOADDOWNLOAD_SUCCESS, CanMessageBuffer, 0);
		IsUploadApplication = 0;
		break;
	case CAN_DOWNLOAD_START_APPLICATION:
		//Read the application size at the 0x08004000 address.
		ReadFlash8Bytes(FLASH_APPLICATION_SIZE_ADDRESS, CanMessageBuffer);
		SendCanMessage(CAN_DEV_ANALYST, CAN_DOWNLOAD_START_APPLICATION, CanMessageBuffer, 8);
		DownloadApplicationWaitCounter = MAX_COUNTDOWN;
		IsDownloadApplication = 1;
		break;
	case CAN_DOWNLOADING_APPLICATION:
		//uploading frame Id format : 0x[1B][Target ID (2B)][[Address {4B}]
		//Here, CanRxApplicationDat is offset address to read.
		ReadFlash8Bytes(FLASH_APPLICATION_START_ADDRESS + CanRxApplicationData, CanMessageBuffer);
		SendCanMessage(CAN_DEV_ANALYST, CAN_DOWNLOADING_APPLICATION, CanMessageBuffer, 8);
		break;
		IsDownloadApplication = 0;
	case CAN_DOWNLOAD_END_APPLICATION:
		SendCanMessage(CAN_DEV_ANALYST, CAN_DOWNLOAD_END_APPLICATION, CanMessageBuffer, 8);
		IsDownloadApplication = 0;
		break;
	}
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
int main(void)
{
	InitRCC();
	InitGPIO();

	InitADC();

	InitCAN();

	for (i=0; i < 500; i ++)
	{
		AdcConvertCanAddress();
		if(AddressAdcValue <= MAX_ADC) break;
		WaitMicrosecond(50);
	}


	SendCanMessage(CAN_DEV_ANALYST, 0xBB, CanMessageBuffer, 0);
    /* Loop forever */
	while(1){
		//lets update the heartbeat now
		HeartbeatCounter --;//count down to zero
		if(HeartbeatCounter & 0x1000)
		{
			TurnOnHeartBeatLed;
		}
		else
		{
			TurnOffHeartBeatLed;
			if(!HeartbeatCounter)	HeartbeatCounter = MAX_COUNTDOWN;//reset the counter if we are at zero
		}

    	// we need to put a case here that will fire about 10 times per second
		//it will read the canaddressadc,
		//then update the head address,
		//then send a ping message until it registers

    	CanAddressAdcConvertCounter --; //count down AdcConvertCounter to zero
    	if(!CanAddressAdcConvertCounter)
    	{
    		CanAddressAdcConvertCounter = MAX_COUNTDOWN;

    		AdcConvertCanAddress(); 	//get the head resister value by adc converting.

    		if(AddressAdcValue < 0x7ff) //if successful,
    		{
    			CalculateDevicePosition(); 	//update the device address with that.
				//if(CurrentHeadCanAddress != POSITION_UNPLUGGED)
					//PingCanMessage();			//send the ping message to all device.
    		}
    	}



    	//////////////// Can Message Transmitting Process //////////////////////////////
    	if(CanTrasmitMsgWaitCounter) //if Can is transsming,
    	{
    		status = CAN_TransmitStatus(CAN1, CanTransmitMailbox); //Check the Can Transmit status
    		if((status != CAN_TxStatus_Ok) && (CanTrasmitMsgWaitCounter))
    			CanTrasmitMsgWaitCounter --; //Count down the counter for CAN transmit
    		else if(status == CAN_TxStatus_Ok)
    		{
    			//if Can transmit successfull, set the flag.
    			CanMessageReadyToSend = 1;
    			CanTrasmitMsgWaitCounter = 0; //Can Transmit Status set as Idle.
    		}
    	}
    	if (CanMessageReadyToSend)	//if Can transmitting has done.
		{
			//this will be used in response to a memory read request by the host, over the
			//	can bus bootloader, can bus can only send 8 bytes of data at a time,
			//so we will need a counter and pointer to keep track of what memory to read
			//and when we have sent ALL the requested data.
			CanTxLedStatus = MAX_COUNTDOWN;  //set the semaphore Can Tx Led status
			CanMessageReadyToSend = 0; //clear the Can Message Send flag.
		}

		if(CanMessageReadyToRead) // If Can message received.
		{
			//process the message();
			CanRxLedStatus = MAX_COUNTDOWN;//just guessing, but 10,000 loops should be enough time to see the led.
			CanMessageReadyToRead = 0;  //clear the Can Message Rcv flag.
			processCanMsgFunction();
		}
    	//set the can traffic transmit led on or off
		if(CanTxLedStatus)
		{
			//get here means the led should be on
			SetCanTxLed;
			CanTxLedStatus --;
		}
		else
		{
			//the led has had enough time to be seen, so now we can turn it off
			ClearCanTxLed; //down count the Can Tx Semaphore
		}

		//set the can traffic receive led on or off
		if(CanRxLedStatus)
		{
			//get here means the led should be on
			SetCanRxLed;
			CanRxLedStatus --; //down count the Can Rx Semaphore.
		}else
		{
			//the led has had enough time to be seen, so now we can turn it off
			ClearCanRxLed;
		}
	}
}
